INSERT INTO authority (AUTHORITY_NAME) VALUES ( 'ROLE_USER' );
INSERT INTO authority (AUTHORITY_NAME) VALUES ( 'ROLE_ADMIN' );

INSERT INTO user (USER_ID, EMAIL, ENABLE, PASSWORD, USERNAME) VALUES (1, 'dygks8557@naver.com', true , '$2a$10$3THNdU4D6i3SQjNaQZ4myOGmqPVpJiJKZ8oK9O8qtQCJ1Qalny4MG' , 'jupaka');
INSERT INTO verification_token (ID, UUID, EXPIRY_DATE, USER_ID ) VALUES ( 1, '3b9bc0c4-f9cb-423b-b3b2-13adb6ed5584', null, 1 );

INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) VALUES ( 1, 'ROLE_USER' );

-- INSERT INTO feed (POST_ID, TITLE, POST_DESC, USER_ID) VALUES ( 1, 'TITLE 1', 'DESC 1', 1 );
-- INSERT INTO feed (POST_ID, TITLE, POST_DESC, USER_ID) VALUES ( 2, 'TITLE 2', 'DESC 2', 1 );
-- INSERT INTO feed (POST_ID, TITLE, POST_DESC, USER_ID) VALUES ( 3, 'TITLE 3', 'DESC 3', 1 );
-- INSERT INTO feed (POST_ID, TITLE, POST_DESC, USER_ID) VALUES ( 4, 'TITLE 4', 'DESC 4', 1 );
-- INSERT INTO feed (POST_ID, TITLE, POST_DESC, USER_ID) VALUES ( 5, 'TITLE 5', 'DESC 5', 1 );

